// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace HolyClub.Automacao.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Matchmaking e Sistema de Confiança (Trust Score)")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class MatchmakingESistemaDeConfiancaTrustScoreFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Matchmaking e Sistema de Confiança (Trust Score)", "  Como um jogador competitivo\r\n  Quero ser pareado com jogadores de nível e compo" +
                "rtamento similares\r\n  Para que as partidas sejam justas e livres de toxicidade", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Matchmaking_TrustScore.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("que o sistema de matchmaking está ativo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Matchmaking_TrustScore.feature.ndjson", 9);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Aplicar regra da \"Maçã Podre\" em Lobby misto")]
        [global::NUnit.Framework.CategoryAttribute("RN-MM-01")]
        [global::NUnit.Framework.CategoryAttribute("Critico")]
        [global::NUnit.Framework.CategoryAttribute("Matchmaking")]
        public async global::System.Threading.Tasks.Task AplicarRegraDaMacaPodreEmLobbyMisto()
        {
            string[] tagsOfScenario = new string[] {
                    "RN-MM-01",
                    "Critico",
                    "Matchmaking"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Aplicar regra da \"Maçã Podre\" em Lobby misto", "    O sistema deve nivelar o lobby por baixo para evitar \"boosting\" por cheaters." +
                    "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 14
    await testRunner.GivenAsync("que o jogador \"Sombra\" tem Trust Score \"Excellent\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 15
    await testRunner.AndAsync("o jogador \"Tóxico_01\" tem Trust Score \"Restricted\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 16
    await testRunner.WhenAsync("eles formam um lobby juntos para buscar partida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 17
    await testRunner.ThenAsync("o sistema deve considerar o Trust Score do lobby como \"Restricted\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 18
    await testRunner.AndAsync("o pareamento deve buscar oponentes com status \"Restricted\" ou inferior", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Sandbox para contas novas (Cold Start)")]
        [global::NUnit.Framework.CategoryAttribute("RN-MM-03")]
        [global::NUnit.Framework.CategoryAttribute("AntiSmurf")]
        public async global::System.Threading.Tasks.Task SandboxParaContasNovasColdStart()
        {
            string[] tagsOfScenario = new string[] {
                    "RN-MM-03",
                    "AntiSmurf"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Sandbox para contas novas (Cold Start)", "    Contas novas não devem jogar contra veteranos imediatamente.", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.GivenAsync("que o jogador \"Novato_Steam\" possui apenas 5 partidas jogadas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 25
    await testRunner.WhenAsync("ele iniciar a busca por uma partida casual", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 26
    await testRunner.ThenAsync("o sistema deve restringir a busca apenas a outros jogadores com menos de 10 parti" +
                        "das", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 27
    await testRunner.AndAsync("jogadores com Trust Score \"Neutral\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Escala progressiva de banimento por abandono")]
        [global::NUnit.Framework.CategoryAttribute("RN-PEN-01")]
        [global::NUnit.Framework.CategoryAttribute("Penalidade")]
        [global::NUnit.Framework.TestCaseAttribute("0", "30 minutos", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("1", "2 horas", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("2", "24 horas", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("3", "7 dias", "5", null)]
        public async global::System.Threading.Tasks.Task EscalaProgressivaDeBanimentoPorAbandono(string reincidencia, string tempo_Banimento, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RN-PEN-01",
                    "Penalidade"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("reincidencia", reincidencia);
            argumentsOfScenario.Add("tempo_banimento", tempo_Banimento);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Escala progressiva de banimento por abandono", "    A punição deve aumentar conforme a reincidência.", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
    await testRunner.GivenAsync(string.Format("que o jogador \"Leaver\" possui {0} abandonos prévios ativos", reincidencia), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 34
    await testRunner.WhenAsync("ele abandonar uma partida em andamento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 35
    await testRunner.ThenAsync(string.Format("ele deve receber um banimento temporário de {0}", tempo_Banimento), ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Bloqueio de Hardware (Shadowban)")]
        [global::NUnit.Framework.CategoryAttribute("RN-PEN-03")]
        [global::NUnit.Framework.CategoryAttribute("Seguranca")]
        [global::NUnit.Framework.CategoryAttribute("HWID")]
        public async global::System.Threading.Tasks.Task BloqueioDeHardwareShadowban()
        {
            string[] tagsOfScenario = new string[] {
                    "RN-PEN-03",
                    "Seguranca",
                    "HWID"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bloqueio de Hardware (Shadowban)", "    Se um PC foi usado para cheat, outras contas nele devem ser penalizadas.", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 48
    await testRunner.GivenAsync("que a máquina com HWID \"PC-X99\" teve uma conta banida por Cheat permanentemente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 49
    await testRunner.WhenAsync("o jogador \"Inocente_Fake\" logar nesta mesma máquina \"PC-X99\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 50
    await testRunner.ThenAsync("o sistema deve identificar o vínculo de hardware", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 51
    await testRunner.AndAsync("alterar o Trust Score da conta \"Inocente_Fake\" para \"Suspicious\" imediatamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
